name: Scheduled Update

on:
  schedule:
    - cron: "0 */16 * * *"
  workflow_dispatch:

jobs:
  updates:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install --frozen-lockfile
      - run: bun run ./src/index.ts
        env:
          IZLY_WEBHOOK: ${{ secrets.IZLY_WEBHOOK }}

      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A

          if git diff --staged --quiet; then
            echo "no updates."
          else
            git commit -m "chore: sync versions"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
